rugindia/urls.py
from django.contrib import admin
from django.urls import path , re_path
from django.conf.urls import include
from django.conf.urls.static import static
from rugs import urls 
from django.conf import settings

from django_otp.admin import OTPAdminSite
  
admin.site.__class__ = OTPAdminSite
urlpatterns = [
    path('ragkallak/controlpanel/admin/', admin.site.urls),
    path('', include('rugs.urls')),
   
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

rugs/urls.py
from .views import HomeView,ProductView ,AboutView,ContactView,ResetPasswordView
from django.urls import path
from . import views
app_name="rugs"
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('products/<str:des>/',ProductView.as_view(),name='products'),
    path('aboutus', AboutView.as_view(),name='about'),
    path('contact',ContactView.as_view(),name='contact'),
   path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
 
]

rugs/models.py
from django.db import models
import os 
from django.utils.safestring import mark_safe
# Create your models here.

PROJECT_DIR =os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
  
class Products(models.Model):
    name= models.CharField( max_length=64, unique=True,verbose_name="Enter the Categories Name")
    class  Meta:  #new
        verbose_name_plural  =  "PRODUCTS NAME" 
 
    def __str__(self):
        return f" {self.name}"

class Home(models.Model):
    pagetitle=models.CharField(max_length=60,verbose_name="Enter the Page Sub Heading")
    pagetext =models.CharField( max_length=1000,verbose_name="Enter Page  Description")
    class  Meta:  #new
        verbose_name_plural  =  "HOME PAGE TITLE AND DESCRIPTION" 
    def __str__(self):
        return f"PAGE TITLE:{self.pagetitle} AND PAGE TEXT:{self.pagetext}"

class AboutUs(models.Model):
    pagetitle=models.CharField(max_length=60,verbose_name="Enter the Page Sub Heading")
    pagetext =models.CharField( max_length=1000,verbose_name="Enter Page  Description")
    class  Meta:  #new
        verbose_name_plural  =  "ABOUT-US PAGE TITLE AND DESCRIPTION"   
    def __str__(self):
        return f"PAGE TITLE:{self.pagetitle} "
            

class contact(models.Model):
    pagetitle=models.CharField(max_length=60,verbose_name="Enter the Page Sub Heading")
    pagetext = models.CharField(max_length =1000, verbose_name="Enter Page  Description")
    class  Meta:  #new
        verbose_name_plural  =  "CONTACT PAGE TITLE AND DESCRIPTION" 
    def __str__(self):
        return f"PAGE TITLE:{self.pagetitle} "

class carousels(models.Model):
    Image = models.ImageField(upload_to=os.path.join(PROJECT_DIR, "frontend/img"), null = True,verbose_name="Enter The Image for carousel")
    Img_title = models.CharField(max_length=30, null=True,verbose_name="Enter The image title")
    Img_desc = models.CharField(max_length=500, null=True,verbose_name="Enter The image description",blank=True)
    class  Meta:  #new
        verbose_name_plural  =  "CAROUSELS IMAGES" 
    def __str__(self):
        return f"IMAGE : {self.Image}   TITLE:{self.Img_title} "
    def car_preview(self): #new
        return mark_safe(f'<img src = "{self.Image.url}" width = "100"/>')
    
class banner_one(models.Model):
    b_title=models.CharField(max_length=60,verbose_name="Enter the Banner Heading")
    b_img1=models.ImageField(upload_to=os.path.join(PROJECT_DIR, "frontend/img"),verbose_name="Enter The First Image for Banner")
    b_img2=models.ImageField(upload_to=os.path.join(PROJECT_DIR, "frontend/img"),verbose_name="Enter The First Image for Banner")
    b_img3=models.ImageField(upload_to=os.path.join(PROJECT_DIR, "frontend/img"),verbose_name="Enter The First Image for Banner")
    class  Meta:  #new
        verbose_name_plural  =  "BANNER ONE" 
    
    def __str__(self):
        return f" BANNER NAME :{self.b_title}"
    def car_preview(self): #new
        return mark_safe(f'<img src = "{self.b_img1.url}" width = "100"/>')

class banner_two(models.Model):
    b_title=models.CharField(max_length=60,verbose_name="Enter the Banner heading")
    b_img1=models.ImageField(upload_to=os.path.join(PROJECT_DIR, "frontend/img"),verbose_name="Enter The First Image for Banner")
    b_img2=models.ImageField(upload_to=os.path.join(PROJECT_DIR, "frontend/img"),verbose_name="Enter The First Image for Banner")
    b_img3=models.ImageField(upload_to=os.path.join(PROJECT_DIR, "frontend/img"),verbose_name="Enter The First Image for Banner")
    def car_preview(self): #new
        return mark_safe(f'<img src = "{self.b_img1.url}" width = "100"/>   ')

class headers(models.Model):
    title_img=models.ImageField(upload_to=os.path.join(PROJECT_DIR, "frontend/img"),verbose_name="Enter The TITLE IMAGE")
    logo=models.ImageField(upload_to=os.path.join(PROJECT_DIR, "frontend/img"),verbose_name="Enter The Logo")
    email=models.EmailField(max_length=256,verbose_name="Enter The Email id",null=True,blank=True)
    insta=models.URLField(max_length=500,verbose_name="Enter The Instagram  Profile URl",null=True,blank=True)
    facebook=models.URLField(max_length=500,verbose_name="Enter The FaceBook Profile URl",null=True,blank=True)
    twitter=models.URLField(max_length=500,verbose_name="Enter The twitter  Profile URl",null=True,blank=True)
    class  Meta:  #new
        verbose_name_plural  =  "LOGO IMAGE AND SOCIAL MEDIA LINKS" 
    
    def __str__(self):
        return f" email: {self.email}; instagram : {self.insta}; facebook :{self.facebook}; twitter:{self.twitter}"
    
    def logo_preview(self): #new
        return mark_safe(f'<img src = "{self.logo.url}" width = "100"/>')
    def title_preview(self): #new
        return mark_safe(f'<img src = "{self.title_img.url}" width = "50"/>')


class Images(models.Model):
    title=models.CharField(max_length=30,verbose_name="Enter The image title",blank=True  )
    desp =models.CharField( max_length=250,verbose_name="Enter Image Description",blank=True )
    image=models.ImageField(upload_to=os.path.join(PROJECT_DIR, "frontend/img"))
    des = models.ForeignKey(Products,on_delete=models.CASCADE )
   
    class  Meta:  #new
        verbose_name_plural  =  "PRODUCTS IMAGES" 
    
    def __str__(self):
        return f"IMAGE : {self.image} TITLE:{self.title} DESCRIPTION:{self.desp}  PRODUCT NAME:{self.des}"
    
    def img_preview(self): #new
        return mark_safe(f'<img src = "{self.image.url}" width = "300"/>')
    

rugs/views.py
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from .models import Products ,Images, Home,AboutUs, carousels, contact, headers,banner_one,banner_two
from django.http import HttpResponse
from django.views.generic import ListView,DetailView

from django.shortcuts import render

class HomeView(ListView):
    http_method_names = ["get"]
    model=Home
    template_name ='rugs/dashboard.html'
    context_object_name = "home"
    def __str__(self):
      return str(self.id)
    
    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context[  'carousels' ] = carousels.objects.all()
        context[  'items' ] = Products.objects.all()
        context[  'head' ] = headers.objects.all()
        context[  'pic']  = Images.objects.all()
        context[ 'banner1'] = banner_one.objects.all()
        context[ 'banner2'] = banner_two.objects.all()
        return context

class ProductView(ListView):
    template_name = 'rugs/products.html'
    context_object_name = 'product'
    model=Images
    slug_field="des"
    slug_url_kwarg="des"
   
    def get_queryset(self):
        return Images.objects.filter(des_id=self.kwargs['des'])
    
    
    def get_context_data(self, **kwargs):
        context = super(ProductView, self).get_context_data(**kwargs)
        context[  'carousels' ] = carousels.objects.all()
        context[  'items' ] = Products.objects.all()
        context[  'head' ] = headers.objects.all()
        
        return context
    
    
class ContactView(ListView):
    http_method_names =["get"]
    model=contact
    template_name="rugs/contact.html"
    context_object_name = "contacts"

    def get_context_data(self, **kwargs):
        context = super(ContactView, self).get_context_data(**kwargs)
        context[  'carousels' ] = carousels.objects.all()
        context[  'items' ] = Products.objects.all()
        context[  'head' ] = headers.objects.all()
        
        return context
        return context

class AboutView(ListView):
    http_method_names =["get"]
    model=AboutUs
    template_name="rugs/aboutus.html"
    context_object_name = "abouts"

    def get_context_data(self, **kwargs):
        context = super(AboutView, self).get_context_data(**kwargs)
        context[  'carousels' ] = carousels.objects.all()
        context[  'items' ] = Products.objects.all()
        context[  'head' ] = headers.objects.all()
        
        return context
    
class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    subject_template_name = 'users/password_reset_subject'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('users-home')




    

rugs/templates/rugs/parts/carousel.html
{% load static %}



 

rugs/templates/rugs/parts/footer.html
{% load  static %}

          










 
    
        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        
        <symbol id="facebook" viewBox="0 0 16 16">
            <path  fill-rule="evenodd"d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
        </symbol>
        <symbol id="instagram" viewBox="0 0 16 16">
            <path  fill-rule="evenodd" d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
        </symbol>
        <symbol id="twitter" viewBox="0 0 16 16">
            <path  fill-rule="evenodd" d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
        </symbol>
        <symbol id="gmail" viewBox="0 0 16 16">
            <path d="M2 2A2 2 0 0 0 .05 3.555L8 8.414l7.95-4.859A2 2 0 0 0 14 2H2Zm-2 9.8V4.698l5.803 3.546L0 11.801Zm6.761-2.97-6.57 4.026A2 2 0 0 0 2 14h6.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.606-3.446l-.367-.225L8 9.586l-1.239-.757ZM16 9.671V4.697l-5.803 3.546.338.208A4.482 4.482 0 0 1 12.5 8c1.414 0 2.675.652 3.5 1.671Z"/>
            <path   fill-rule="evenodd" d="M15.834 12.244c0 1.168-.577 2.025-1.587 2.025-.503 0-1.002-.228-1.12-.648h-.043c-.118.416-.543.643-1.015.643-.77 0-1.259-.542-1.259-1.434v-.529c0-.844.481-1.4 1.26-1.4.585 0 .87.333.953.63h.03v-.568h.905v2.19c0 .272.18.42.411.42.315 0 .639-.415.639-1.39v-.118c0-1.277-.95-2.326-2.484-2.326h-.04c-1.582 0-2.64 1.067-2.64 2.724v.157c0 1.867 1.237 2.654 2.57 2.654h.045c.507 0 .935-.07 1.18-.18v.731c-.219.1-.643.175-1.237.175h-.044C10.438 16 9 14.82 9 12.646v-.214C9 10.36 10.421 9 12.485 9h.035c2.12 0 3.314 1.43 3.314 3.034v.21Zm-4.04.21v.227c0 .586.227.8.581.8.31 0 .564-.17.564-.743v-.367c0-.516-.275-.708-.572-.708-.346 0-.573.245-.573.791Z"/>
        </symbol>
        </svg>

        <div class="container  bg-black p-3" data-bs-theme="dark"   aria-pressed="false">
            <footer class=" bg-black d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top text-white text-decoration-none">
                <div class=" bg-black col-md-4 d-flex align-items-center">
                    <span class=" bg-blackmb-3 mb-md-0 text-body-secondary "><img src="{% for h in head %}
                        {{h.logo.url}}
                        {% endfor %} " width=200></span>
                 </div>
                 
                <ul class="  bg-black  nav col-md-4 justify-content-end list-unstyled d-flex">
                  <!--  {% for x in head %}
                   {% if  x.twitter == null %}
                    <li class="ms-3 " style="display: none;"><a class=" text-body-secondary hidden"target="_blank" rel="noopener noreferrer" href="{% for x in head %}{{x.twitter}}{% endfor %}"><svg class="bi d-block mx-auto mb-1" fill="white" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
                    {% else %}
                    <li class="ms-3 "><a class="text-body-secondary raise " type="button" target="_blank" rel="noopener noreferrer" href="{% for x in head %}{{x.twitter}}{% endfor %}"><svg class="bi d-block mx-auto mb-1" fill="white" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
                    {% endif %}
                     
                    
                    {% if x.insta == null %}
                    <li class="ms-3"><a class=" text-body-secondary hidden" target="_blank" rel="noopener noreferrer" href="{% for x in head %}{{x.insta}}{% endfor %}"><svg class=" bi d-block mx-auto mb-1"fill="white" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
                    {% else %}
                    <li class="ms-3"><a class=" text-body-secondary raise" type="button" target="_blank" rel="noopener noreferrer" href="{% for x in head %}{{x.insta}}{% endfor %}"><svg class=" bi d-block mx-auto mb-1" fill="white"width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>

                    {% endif %}

                    
                    {% if x.facebook == null  %}
                    <li class="ms-3" style="display: none;"><a class="text-body-secondary hidden" target="_blank" rel="noopener noreferrer" href="{% for x in head %}{{x.facebook}}{% endfor %}"><svg class="bi" width="24" fill="white"height="24"><use xlink:href="#facebook"/></svg></a></li>
                    {% else %}
                    <li class="ms-3"><a class=" text-body-secondary raise" type="button" target="_blank" rel="noopener noreferrer" href="{% for x in head %}{{x.facebook}}{% endfor %}"><svg class="bi"fill="white" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>

                    {% endif %}

                    
                    {% if x.email == null %}
                    <li class="ms-3"><a class=" text-body-secondary hidden " target="_blank" rel="noopener noreferrer" href="mailto:{% for x in head %} {{x.email}}{% endfor %}"><svg class="bi" fill="white" width="24" height="24"><use xlink:href="#gmail"/></svg></a></li>
                     {% else %}   
                     <li class="ms-3"><a class=" text-body-secondary raise " type="button" target="_blank" rel="noopener noreferrer" href="mailto:{% for x in head %} {{x.email}}{% endfor %}"><svg class="bi" fill="white" width="24" height="24"><use xlink:href="#gmail"/></svg></a></li>

                    {% endif %}
                        
                        
                        
                    {% endfor %} -->
                  
                </ul>
            </footer>
        </div>
   

rugs/templates/rugs/parts/header.html
{% load static %}




<style> .dropcolor{
    color:white;
   }
   .dropcolor:hover{
    color:black;
    
   }</style>










    <header>
        <link herf ="{% static "css/head1.css" %}" rel="stylesheet">  
    
        <svg xmlns="http://www.w3.org/2000/svg" fill="white" style="display: none;">
            <symbol id="bootstrap" viewBox="0 0 118 94">
                <title>Bootstrap</title>
                <path fill="white" fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
            </symbol>
        
            <symbol id="home" viewBox="0 0 16 16">
                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L8 2.207l6.646 6.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5Z"/>
                <path d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6Z"/>
            </symbol>
        
            <symbol id="people-circle" viewBox="0 0 16 16">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
            </symbol>
        
            <symbol id="speedometer2" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511zm9.261 1.135a.5.5 0 0 1 .708 0L13 2.793l1.146-1.147a.5.5 0 0 1 .708.708L13.707 3.5l1.147 1.146a.5.5 0 0 1-.708.708L13 4.207l-1.146 1.147a.5.5 0 0 1-.708-.708L12.293 3.5l-1.147-1.146a.5.5 0 0 1 0-.708z"/>
            </symbol>
            
            
            <symbol id="grid" viewBox="0 0 16 16">
                <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"/>
            </symbol>
    
        </svg>
    
        <div class="  px-3 py-2 text-bg-dark border-bottom bg-black ">
            <div class="container">
           
                <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                    <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
                        <img src="{{head.logo.url}} " alt="">
                        <svg fill="white" class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">  
                            <img src="{% for h in head %}
                            {{h.logo.url}}
                            {% endfor %} " width=200> </svg>
                    </a>
        
                    <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
        
                        <li>
                            <a href="{% url 'rugs:home' %}" class=" text-white nav-link bi raise">
                                <svg class=" d-block mx-auto mb-1  " fill="white" width="24" height="24"><use xlink:href="#home"/></svg>
                                Home 
                            </a>
                        </li>
            
                    
                            
                        <li class="nav-item dropdown">
                            <a  class="nav-link text-white dropdown-toggle raise"  role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg class="bi d-block mx-auto mb-1 dropdown-toggle" fill="white" width="24" height="24">
                                    <use xlink:href="#grid"/>
                                </svg>
                                Products
                            </a>
                            <ul class="dropdown-menu  text-bg-dark " >
                                
                                {% for item in items %}
                                 <li><a class="dropdown-item dropcolor  " href=" {% url 'rugs:products' item.id %} "> {{item.name|safe}} </a></li>
                                {% endfor %}
                                
                            
            
                            </ul>
                        </li>
                      
                            
                        
                        
            
                        <li>
                            <a href="{% url 'rugs:contact' %}" class="nav-link text-white raise">
                                <svg class="bi d-block mx-auto mb-1" fill="white" width="24" height="24"><use xlink:href="#speedometer2"/></svg>
                                Contact Us
                            </a>
                        </li>
            
                        
                        <li>
                            <a href="{% url 'rugs:about' %}" class="nav-link text-white raise">
                                <svg class="bi d-block mx-auto mb-1" fill="white" width="24" height="24"><use xlink:href="#people-circle"/></svg>
                                About Us 
                            </a>
                        </li>
        
                    </ul>
                </div>
            </div>
        </div>
    </header>